name: dotpay CI process

on:
  #push: 
  #  branches: [feat/merchart-service]
  #pull_request:
  #  branches: [develop, main]
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest source
        uses: actions/checkout@v4

      - name: Setup .NET  Core SDK
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore
        run: dotnet restore src/MerchantService/MerchatService.API
