name: dotpay CI process
on:
  workflow_dispatch:
  push:
    branches:
      - feat/merchart-service
      - feat/kyc-service
  pull_request:
    branches:
      - develop
      - main
      - feat/merchart-service
      - feat/kyc-service

jobs:
  # 1) Determine which services changed
  filter:
    runs-on: ubuntu-latest
    outputs:
      merchant: ${{ steps.paths.outputs.merchant }}
      kyc:      ${{ steps.paths.outputs.kyc }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Path filter
        id: paths
        uses: dorny/paths-filter@v2
        with:
          filters: |
            merchant:
              - 'src/MerchantService/**'
            kyc:
              - 'src/KYCService/**'

  # 2) Build & test only the changed services via a matrix
  build:
    needs: filter
    runs-on: ubuntu-latest
    # define one row per service, with the key that matches the filter output
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: MerchantService
            filterKey: merchant
            csproj:    src/MerchantService/MerchatService.API/MerchatService.API.csproj
            folder:    src/MerchantService
          - name: KYCService
            filterKey: kyc
            csproj:    src/KycService/KycService.csproj
            folder:    src/KycService

    steps:
      - name: Checkout code
        if: ${{ needs.filter.outputs[matrix.service.filterKey] == 'true' }}
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        if: ${{ needs.filter.outputs[matrix.service.filterKey] == 'true' }}
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies ( ${{ matrix.service.name }} )
        if: ${{ needs.filter.outputs[matrix.service.filterKey] == 'true' }}
        run: dotnet restore ${{ matrix.service.csproj }}

      - name: Lint ( ${{ matrix.service.name }} )
        if: ${{ needs.filter.outputs[matrix.service.filterKey] == 'true' }}
        run: dotnet format --verify-no-changes ${{ matrix.service.csproj }}

      - name: Build ( ${{ matrix.service.name }} )
        if: ${{ needs.filter.outputs[matrix.service.filterKey] == 'true' }}
        run: dotnet build --no-restore ${{ matrix.service.csproj }}

      - name: Unit Tests ( ${{ matrix.service.name }} )
        if: ${{ needs.filter.outputs[matrix.service.filterKey] == 'true' }}
        run: dotnet test --no-build --verbosity normal ${{ matrix.service.folder }}

